export const ActionTypes={

    FETCH_COUNTRIES:'FETCH_COUNTRIES',
    SELECTED_COUNTRY:'SELECTED_COUNTRY',
    SEARCH_COUNTRY:'SEARCH_COUNTRY',
    SEARCH_COUNTRY_BY_REGION:'SEARCH_COUNTRY_BY_REGION',
    ERROR:"ERROR",
    TOGGLE_DARK_MODE:'TOGGLE_DARK_MODE'

}